CC	=	g++
CFLAGS	=	-Wall
OBJS	=	main.cpp	graphic.cpp	seznam.cpp	
vertex.cpp	
point3.cpp	
graphic.h	
grahamscan.h	point3.h	seznam.h	stack.h	vertex.h

convexhull: ${OBJS}
	${CC} ${CFLAGS} -o -lglut ${OBJS}



